# Generated by Django 5.2.2 on 2025-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_row_seats_movie_session',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='seats',
            new_name='seat',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_row_seat_movie_session'),
        ),
    ]
